# Generated by Django 4.0.6 on 2022-07-21 23:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_ticketed', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('N', 'New'), ('O', 'Open'), ('W', 'Working'), ('C', 'Closed')], default='N', max_length=1)),
                ('ticket_type', models.CharField(choices=[('Service Request Ticket', 'Service Request Ticket'), ('Incident Ticket', 'Incident Ticket'), ('Problem Ticket', 'Problem Ticket'), ('Change Request Ticket', 'Change Request Ticket')], default='IT', max_length=50)),
                ('urgency', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date_replied', models.DateTimeField(default=django.utils.timezone.now)),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket.ticket')),
            ],
        ),
    ]
