# Generated by Django 4.0.6 on 2023-02-17 22:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
