# Generated by Django 4.0.6 on 2023-02-11 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_location',
            field=models.CharField(choices=[('AHL_station_0', 'Ahl_station_1'), ('AHL station_1', 'Ahl_station_2'), ('AHL station_2', 'Ahl_station_3'), ('AHL station_3', 'Ahl_station_4'), ('AHL station_4', 'Ahl_station_5'), ('Stative', 'Stative_station_1'), ('Stative', 'Stative_station_2'), ('Stative', 'Stative_station_3'), ('Stative', 'Stative_station_4'), ('Stative', 'Stative_station_5'), ('1000', '1000_station_1'), ('1000', '1000_station_2'), ('1000', '1000_station_3'), ('1000', '1000_station_4'), ('1000', '1000_station_5'), ('Compact', 'Compact_station_1'), ('Compact', 'Compact_station_2'), ('Compact', 'Compact_station_3'), ('Compact', 'Compact_station_4'), ('Compact', 'Compact_station_5')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Open'), ('W', 'Working'), ('C', 'Closed'), ('D', 'Draft'), ('P', 'Publish')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Tracksys', 'Tracksys'), ('AHL', 'AHL'), ('Stative', 'Stative'), ('Compact', 'Compact'), ('Pack & Plock', 'Pack & Plock'), ('DelMontage', 'DelMontage')], default='Tracksys', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ar Nummer / Plockplats'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(default=1, error_messages={'max_value': 'Välj ett brådskande mellanrum 1 och 10', 'min_value': 'Välj ett brådskande mellanrum 1 och 10'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Brotskande (1-10)'),
        ),
    ]
