# Generated by Django 4.0.6 on 2023-02-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='privacy',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default='0', max_length=1),
        ),
    ]
