# Generated by Django 4.0.6 on 2023-02-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(),
        ),
    ]
