# Generated by Django 4.0.6 on 2023-02-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='privacy',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default='0', max_length=1),
        ),
    ]
