# Generated by Django 4.0.6 on 2023-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_ticket_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_location',
            field=models.CharField(choices=[('ALL', 'ALL'), ('AHL_station_1', 'Ahl_station_2'), ('AHL_station_2', 'Ahl_station_3'), ('Ahl_station_3', 'Ahl_station_4'), ('Ahl_station_4', 'Ahl_station_5'), ('Stative_station_0', 'Stative_station_0'), ('Stative_station_1', 'Stative_station_1'), ('Stative_station_2', 'Stative_station_2'), ('Stative_station_3', 'Stative_station_3'), ('Stative_station_4', 'Stative_station_4'), ('1000_station_0', '1000_station_0'), ('1000_station_1', '1000_station_1'), ('1000_station_2', '1000_station_2'), ('1000_station_3', '1000_station_3'), ('1000_station_4', '1000_station_4'), ('Compact_station_0', 'Compact_station_0'), ('Compact_station_1', 'Compact_station_1'), ('Compact_station_2', 'Compact_station_2'), ('Compact_station_3', 'Compact_station_3'), ('Compact_station_4', 'Compact_station_4')], default='0', max_length=36),
        ),
    ]
