# Generated by Django 4.0.6 on 2023-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='privacy',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'Ny'), ('O', 'Oppet'), ('j', 'Jobbar'), ('s', 'Stängd')], default='N', max_length=1),
        ),
    ]
