# Generated by Django 4.0.6 on 2023-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_image',
            field=models.ImageField(blank=True, upload_to='ticket_pics/%Y/%m/%d/'),
        ),
    ]
