# Generated by Django 4.0.6 on 2023-02-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_ticket_image_ticket_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_image',
            new_name='image',
        ),
    ]
