# Generated by Django 4.0.6 on 2023-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Tracksys', 'Tracksys'), ('AHL', 'AHL'), ('Stative', 'Stative'), ('Compact', 'Compact'), ('Pack & Plock', 'Pack & Plock'), ('DelMontage', 'DelMontage')], default='Tracksys', max_length=50),
        ),
    ]
