# Generated by Django 4.0.6 on 2023-02-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
